REVOKE ALL ON DATABASE test FROM PUBLIC;

REVOKE ALL ON SCHEMA public FROM PUBLIC;

CREATE ROLE dbadmin WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOREPLICATION
  CREATEROLE;
GRANT CONNECT ON DATABASE test TO dbadmin;
GRANT CREATE ON DATABASE test TO dbadmin;
GRANT TEMP ON DATABASE test TO dbadmin;
GRANT dbadmin to postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE dbadmin IN SCHEMA public GRANT SELECT ON TABLES TO dbadmin;

CREATE ROLE readonly WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOREPLICATION
  NOCREATEROLE;
GRANT CONNECT ON DATABASE test TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
GRANT readonly TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE readonly IN SCHEMA public GRANT SELECT ON TABLES TO dbadmin;

CREATE ROLE readwrite WITH
  NOLOGIN
  NOSUPERUSER
  NOCREATEDB
  NOREPLICATION
  NOCREATEROLE;
GRANT CONNECT ON DATABASE test TO readwrite;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readwrite;
GRANT TEMP ON DATABASE test TO readwrite;
GRANT readwrite TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE readonly IN SCHEMA public GRANT SELECT ON TABLES TO dbadmin;

CREATE SCHEMA common AUTHORIZATION dbadmin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA common TO dbadmin;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA common TO dbadmin;

SET ROLE dbadmin;

GRANT USAGE ON SCHEMA common to readonly;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA common to readonly;
GRANT USAGE, SELECT ON ALL TABLES IN SCHEMA common to readonly;

GRANT USAGE ON SCHEMA common to readwrite;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA common to readwrite;
GRANT USAGE, SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA common to readwrite;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA common to readwrite;

SET ROLE postgres;

ALTER DEFAULT PRIVILEGES FOR ROLE dbadmin IN SCHEMA common GRANT ALL PRIVILEGES ON TABLES to dbadmin;
ALTER DEFAULT PRIVILEGES FOR ROLE dbadmin IN SCHEMA common GRANT ALL PRIVILEGES ON FUNCTIONS to dbadmin;


ALTER DEFAULT PRIVILEGES FOR ROLE dbadmin IN SCHEMA common GRANT SELECT ON TABLES to readonly;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA common TO dbadmin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA common TO dbadmin;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA common TO dbadmin;

CREATE USER the_admin WITH PASSWORD 'omg123'
  LOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  INHERIT
  VALID UNTIL 'infinity';
 GRANT dbadmin TO the_admin;

CREATE USER reader WITH PASSWORD 'omg123'
  LOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  INHERIT
  VALID UNTIL 'infinity';
 GRANT readonly TO reader;

CREATE USER writer WITH PASSWORD 'omg123'
  LOGIN
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  INHERIT
  VALID UNTIL 'infinity';
 GRANT readwrite TO writer;
