version: "3"

services:
  base:
    build: ./base
    image: ubuntubase

  nodebase:
    build: ./nodebase
    image: nodebase
    depends_on:
      - base

  webapp:
    build: ./node
    image: webapp
    ports:
      - "3000:3000"
    depends_on:
      - nodebase
