version: '3.5'

services:
  consul1:
    image: consul:latest
    hostname: "consul1"
    container_name: consul1
    volumes:
      - "consul-data:/consul/data"
    networks:
      - consul_network
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: "agent -server -bootstrap-expect 3 -ui -disable-host-node-id -client 0.0.0.0"
  # consul2:
  #   image: consul:latest
  #   hostname: "consul2"
  #   container_name: consul2
  #   networks:
  #     - consul_network
  #   command: "agent -server -join consul1 -disable-host-node-id"
  #   depends_on:
  #     - consul1
  # consul3:
  #   image: consul:latest
  #   hostname: "consul3"
  #   container_name: consul3
  #   networks:
  #     - consul_network
  #   command: "agent -server -join consul1 -disable-host-node-id"
  #   depends_on:
  #     - consul1

networks:
  consul_network:
    name: consul_network

volumes:
  consul-data:
