version: '3.5'

services:
  vault1:
    container_name: vault1
    image: vault
    ports:
      - "8200:8200"
    networks:
      - consul_network
      - vault_network
    cap_add:
      - IPC_LOCK
    environment:
    - VAULT_DEV_ROOT_TOKEN_ID=myroot
    - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200

  bash_test:
    container_name: bash.test
    build:
      context: ./bashtest
    image: bash.test
    environment:
      - CONSUL_HTTP_ADDR=consul1:8500
      - VAULT_ADDR=http://vault1:8200
    networks:
      - consul_network
      - vault_network
    command: tail -f /dev/null

networks:
  consul_network:
    name: consul_network
    external: true

  vault_network:
    name: vault_network
