version: "3.5"

services:
  db:
    build: ./image
    container_name: ${APP_NAME}
    args:
      - app_name=${APP_NAME}
    ports:
      - "5432:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - db_network

volumes:
  ${APP_NAME}-data:
    name: ${APP_NAME}-data

networks:
  ${APP_NAME}-network:
    name: ${APP_NAME}-network
